export const toothpix = [
  {
    name: "In N Out",
    url: "https://www.instagram.com/p/BWXmc58DI21/?utm_source=mp-toothpix",
    address: "13425 Washington Blvd, Marina Del Rey, CA 90292",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 33.9916475,
    longitude: -118.4462335,
    doordashURL: "",
    index: 0,
    streetNumber: "13425 Washington Blvd",
  },
  {
    name: "Canter's Deli",
    url: "https://www.instagram.com/p/BVH0cADD3GP/?utm_source=mp-toothpix",
    address: "419 N Fairfax Ave, Los Angeles, CA 90036",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0787779,
    longitude: -118.3618587,
    doordashURL: "",
    index: 1,
    streetNumber: "419 N Fairfax Ave",
  },
  {
    name: "Animal",
    url: "https://www.instagram.com/p/BVCn3cODquO/?utm_source=mp-toothpix",
    address: "435 N Fairfax Ave, Los Angeles, CA 90036",
    quote:
      "The house restaurant of the Dude District is probably the new Animal, which raises Boy Food to the level of a genuine cuisine \u2014 a farmers-market-intensive version appreciated, it must be said, by a clientele that skews at least two-thirds female: women, after all, are the keenest connoisseurs of testosterone. The chefs, Jon Shook and Vinny Dotolo, who call themselves the Food Dudes, are the Jay and Silent Bob of the food world, perpetually red-eyed and rarely seen outside one another\u2019s company, preparing food or talking about it, slapping up massive catered feasts at Hollywood parties or scheming World Media Domination.",
    la_times_link: "https://www.laweekly.com/animal-boys-in-the-hood/",
    closed: null,
    latitude: 34.0792272,
    longitude: -118.3617507,
    doordashURL: "",
    index: 2,
    streetNumber: "435 N Fairfax Ave",
  },
  {
    name: "Cofax",
    url: "https://www.instagram.com/p/BU9iIV1DiH8/?utm_source=mp-toothpix",
    address: "440 N Fairfax Ave, Los Angeles, CA 90036",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.079339,
    longitude: -118.3612531,
    doordashURL: "",
    index: 3,
    streetNumber: "440 N Fairfax Ave",
  },
  {
    name: "Papa John's",
    url: "https://www.instagram.com/p/BUhJXvXjA4f/?utm_source=mp-toothpix",
    address: "7150 Beverly Blvd, Los Angeles, CA 90036",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0758205,
    longitude: -118.3452944,
    doordashURL: "",
    index: 4,
    streetNumber: "7150 Beverly Blvd",
  },
  {
    name: "Baja Fresh",
    url: "https://www.instagram.com/p/BUHZmq_jdA2/?utm_source=mp-toothpix",
    address: "13424 Maxella Ave, Marina Del Rey, CA 90292",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 33.9863406,
    longitude: -118.4401605,
    doordashURL: "",
    index: 5,
    streetNumber: "13424 Maxella Ave",
  },
  {
    name: "Sapp's Coffee Shop",
    url: "https://www.instagram.com/p/BTjWfmPD5J9/?utm_source=mp-toothpix",
    address: "5183 Hollywood Blvd, Los Angeles, CA 90027",
    quote:
      "Thai Town\u2019s boat-noodle wars show no signs of abating, and there may be no end of Thai caf\u00e9s in the neighborhood claiming to serve the best, the most authentic version, but the homely virtues of Sapp become more apparent by the year. Sapp\u2019s boat noodles are magnificent: murky, organ-rich beef soup amplified with shrieking chile heat, thickened with blood, the tartness of lime juice locked in muscular poise with the brawny muskiness of the broth. Sapp may be the best lunchroom in Hollywood, crowded at noon not with revelers but with people who have come to Thai Town to shop and eat the boat noodles, the grilled chicken and the bright-green \u201cjade\u201d noodles tossed with bits of Chinese barbecue",
    la_times_link: "https://www.laweekly.com/beauty-and-the-boat-noodles/",
    closed: null,
    latitude: 34.1020837,
    longitude: -118.3031667,
    doordashURL: "",
    index: 6,
    streetNumber: "5183 Hollywood Blvd",
  },
  {
    name: "The Apple Pan",
    url: "https://www.instagram.com/p/BSi-innD7zm/?utm_source=mp-toothpix",
    address: "10801 W Pico Blvd, Los Angeles, CA 90064",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0406896,
    longitude: -118.4278502,
    doordashURL: "",
    index: 7,
    streetNumber: "10801 W Pico Blvd",
  },
  {
    name: "Son of a Gun",
    url: "https://www.instagram.com/p/BRvexTijDh7/?utm_source=mp-toothpix",
    address: "8370 W 3rd St, Los Angeles, CA 90048",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0727023,
    longitude: -118.3725117,
    doordashURL: "",
    index: 8,
    streetNumber: "8370 W 3rd St",
  },
  {
    name: "California Donuts",
    url: "https://www.instagram.com/p/BRGYyL-Dild/?utm_source=mp-toothpix",
    address: "3540 W 3rd St, Los Angeles, CA 90020",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0687591,
    longitude: -118.2931096,
    doordashURL: "",
    index: 9,
    streetNumber: "3540 W 3rd St",
  },
  {
    name: "Salazar",
    url: "https://www.instagram.com/p/BQf0nQwhaYN/?utm_source=mp-toothpix",
    address: "2490 Fletcher Dr, Los Angeles, CA 90039",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.107381,
    longitude: -118.2544211,
    doordashURL: "",
    index: 10,
    streetNumber: "2490 Fletcher Dr",
  },
  {
    name: "Destroyer",
    url: "https://www.instagram.com/p/BQQT8Oyhmdv/?utm_source=mp-toothpix",
    address: "3578 Hayden Ave, Culver City, CA 90232",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.024493,
    longitude: -118.3811129,
    doordashURL: "",
    index: 11,
    streetNumber: "3578 Hayden Ave",
  },
  {
    name: "Providence",
    url: "https://www.instagram.com/p/BPsanArBB9C/?utm_source=mp-toothpix",
    address: "5955 Melrose Ave, Los Angeles, CA 90038",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0836552,
    longitude: -118.3302427,
    doordashURL: "",
    index: 12,
    streetNumber: "5955 Melrose Ave",
  },
  {
    name: "Squirl",
    url: "https://www.instagram.com/p/BNuMwvih5UG/?utm_source=mp-toothpix",
    address: "720 N Virgil Ave #4, Los Angeles, CA",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0842609,
    longitude: -118.286624,
    doordashURL: "",
    index: 13,
    streetNumber: "720 N Virgil Ave #4",
  },
  {
    name: "Zankou Chicken",
    url: "https://www.instagram.com/p/BNhVuylhBh5/?utm_source=mp-toothpix",
    address: "5065 Sunset Blvd, Los Angeles, CA 90027",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0985536,
    longitude: -118.3002571,
    doordashURL: "",
    index: 14,
    streetNumber: "5065 Sunset Blvd",
  },
  {
    name: "RiceBar",
    url: "https://www.instagram.com/p/BM9MLYvB1os/?utm_source=mp-toothpix",
    address: "419 7th St, Los Angeles, CA 90014",
    quote: null,
    la_times_link: null,
    closed: "x",
    latitude: 34.0463449,
    longitude: -118.2548324,
    doordashURL: "",
    index: 15,
    streetNumber: "419 7th St",
  },
  {
    name: "Kate Mantilini's",
    url: "https://www.instagram.com/p/BMEdFQJhy-u/?utm_source=mp-toothpix",
    address: "9101 Wilshire Blvd, Beverly Hills, CA 90210",
    quote: null,
    la_times_link: null,
    closed: "x",
    latitude: 34.0674526,
    longitude: -118.3899651,
    doordashURL: "",
    index: 16,
    streetNumber: "9101 Wilshire Blvd",
  },
  {
    name: "Howlin' Rays",
    url: "https://www.instagram.com/p/BLwB_ZDhOze/?utm_source=mp-toothpix",
    address: "727 N Broadway Children's Seating, Los Angeles, CA 90012",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0615147,
    longitude: -118.2397157,
    doordashURL: "",
    index: 17,
    streetNumber: "727 N Broadway Children's Seating",
  },
  {
    name: "Musso & Frank Grill",
    url: "https://www.instagram.com/p/BLG9ejFBaGk/?utm_source=mp-toothpix",
    address: "6667 Hollywood Blvd, Hollywood, CA 90028",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.1018304,
    longitude: -118.3354085,
    doordashURL: "",
    index: 18,
    streetNumber: "6667 Hollywood Blvd",
  },
  {
    name: "Chengdu Taste",
    url: "https://www.instagram.com/p/BK6E1f_hVUb/?utm_source=mp-toothpix",
    address: "828 W Valley Blvd, Alhambra, CA 91803",
    quote:
      "If your experience of Sichuan food is mostly from the Chongqing-style places that have popped up in the San Gabriel Valley in the last few years, you will probably find this Chengdu-style cooking lighter, cleaner and less likely to wake you up in the middle of the night with chile-oil induced nightmares. The food is still quite spicy, flavored with a vast array of fresh, dried, pickled and ground chiles, but the vivid scent of Sichuan peppercorn comes to the front in quite a few dishes, and the overwhelming sensation, even in dishes common to both kinds of restaurants, like the sliced beef in chile oil called fu qi fei pian, mapo tofu, or the chile-accented room-temperature noodles called dan dan mian, is of numbness rather than pain",
    la_times_link: null,
    closed: null,
    latitude: 34.0778469,
    longitude: -118.1324304,
    doordashURL: "",
    index: 19,
    streetNumber: "828 W Valley Blvd",
  },
  {
    name: "Trois Familia",
    url: "https://www.instagram.com/p/BKn7ejcgzr9/?utm_source=mp-toothpix",
    address: "3510 Sunset Blvd., Los Angeles, CA",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0888679,
    longitude: -118.2769866,
    doordashURL: "",
    index: 20,
    streetNumber: "3510 Sunset Blvd.",
  },
  {
    name: "Baroo",
    url: "https://www.instagram.com/p/BKYm45iAsq1/?utm_source=mp-toothpix",
    address: "4632 Santa Monica Blvd, Los Angeles, CA 90029",
    quote:
      "Noorook tastes like nothing I have ever come across. But it does taste like the future. And whether the future it points to might be idyllic or dystopian, one of utopian bliss or one of nutrislime cultivated in jars when the radiation forces us all into underground caves, I am not prepared to say. But I do know that I like this noorook. I have ordered it every time I have been to Baroo. I recommend that you do the same",
    la_times_link: null,
    closed: null,
    latitude: 34.0906198,
    longitude: -118.2903921,
    doordashURL: "",
    index: 21,
    streetNumber: "4632 Santa Monica Blvd",
  },
  {
    name: "Grand Central Market",
    url: "https://www.instagram.com/p/BKTXYGGAbhY/?utm_source=mp-toothpix",
    address: "317 S Broadway, Los Angeles, CA 90013",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0506511,
    longitude: -118.2486879,
    doordashURL: "",
    index: 22,
    streetNumber: "317 S Broadway",
  },
  {
    name: "Pollo a La Brasa",
    url: "https://www.instagram.com/p/BJ-081ZA5aC/?utm_source=mp-toothpix",
    address: "764 S Western Ave, Los Angeles, CA 90005",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0578977,
    longitude: -118.3088981,
    doordashURL: "",
    index: 23,
    streetNumber: "764 S Western Ave",
  },
  {
    name: "Tito's Tacos",
    url: "https://www.instagram.com/p/BJ3O6l4gM4G/?utm_source=mp-toothpix",
    address: "11222 Washington Pl, Culver City, CA 90230",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0081386,
    longitude: -118.4144619,
    doordashURL: "",
    index: 24,
    streetNumber: "11222 Washington Pl",
  },
  {
    name: "Kogi Truck",
    url: "https://www.instagram.com/p/BJiig7hgpZm/?utm_source=mp-toothpix",
    address: "1515 Abbot Kinney Blvd, Venice, CA 90291",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 33.9903819,
    longitude: -118.4641554,
    doordashURL: "",
    index: 25,
    streetNumber: "1515 Abbot Kinney Blvd",
  },
  {
    name: "Pok Pok LA",
    url: "https://www.instagram.com/p/BJdel_WADcU/?utm_source=mp-toothpix",
    address: "978 N Broadway, Los Angeles, CA 90012",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0660651,
    longitude: -118.2358426,
    doordashURL: "",
    index: 26,
    streetNumber: "978 N Broadway",
  },
  {
    name: "Mapo Galbi",
    url: "https://www.instagram.com/p/BJS_ESrARDW/?utm_source=mp-toothpix",
    address: "1008 S St Andrews Pl, Los Angeles, CA 90019",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0523023,
    longitude: -118.310848,
    doordashURL: "",
    index: 27,
    streetNumber: "1008 S St Andrews Pl",
  },
  {
    name: "Wang Xing Ji Juicy Dumplings",
    url: "https://www.instagram.com/p/BJLhFc7AN5l/?utm_source=mp-toothpix",
    address: "140 W Valley Blvd Ste 211, San Gabriel, CA 91776",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0780317,
    longitude: -118.101519,
    doordashURL: "",
    index: 28,
    streetNumber: "140 W Valley Blvd Ste 211",
  },
  {
    name: "Gjusta",
    url: "https://www.instagram.com/p/BJDgchhAbnD/?utm_source=mp-toothpix",
    address: "320 Sunset Ave, Venice, CA 90291",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 33.9951893,
    longitude: -118.4744664,
    doordashURL: "",
    index: 29,
    streetNumber: "320 Sunset Ave",
  },
  {
    name: "Jon and Vinny's",
    url: "https://www.instagram.com/p/BI-wjL2AHfC/?utm_source=mp-toothpix",
    address: "412 N Fairfax Ave, Los Angeles, CA 90036",
    quote: null,
    la_times_link:
      "https://www.latimes.com/food/la-fo-gold-jon-vinnys-20150627-story.html",
    closed: null,
    latitude: 34.0786321,
    longitude: -118.3612417,
    doordashURL: "",
    index: 30,
    streetNumber: "412 N Fairfax Ave",
  },
  {
    name: "Trois Mec",
    url: "https://www.instagram.com/p/BI-v8t4gPSX/?utm_source=mp-toothpix",
    address: "716 N Highland Ave, Los Angeles, CA 90038",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.084231,
    longitude: -118.3380904,
    doordashURL: "",
    index: 31,
    streetNumber: "716 N Highland Ave",
  },
  {
    name: "Yogurtland",
    url: "https://www.instagram.com/p/BI-ZnihAKKL/?utm_source=mp-toothpix",
    address: "1132 N Vermont Ave, Los Angeles, CA 90029",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.091863,
    longitude: -118.2914197,
    doordashURL: "",
    index: 32,
    streetNumber: "1132 N Vermont Ave",
  },
  {
    name: "Sugarfish",
    url: "https://www.instagram.com/p/BI-ZPAqgVL8/?utm_source=mp-toothpix",
    address: "101 South La Brea Ave, Los Angeles, CA 90036",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0733892,
    longitude: -118.3444124,
    doordashURL: "",
    index: 33,
    streetNumber: "101 South La Brea Ave",
  },
  {
    name: "Leo's Tacos",
    url: "https://www.instagram.com/p/BI-YXa7Ad7x/?utm_source=mp-toothpix",
    address: "1515 South La Brea Ave, Los Angeles, CA 90019",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0464051,
    longitude: -118.3457154,
    doordashURL: "",
    index: 34,
    streetNumber: "1515 South La Brea Ave",
  },
  {
    name: "Bestia",
    url: "https://www.instagram.com/p/BI8ErL9ge8l/?utm_source=mp-toothpix",
    address: "2121 E 7th Pl, Los Angeles, CA 90021",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0338622,
    longitude: -118.2293054,
    doordashURL: "",
    index: 35,
    streetNumber: "2121 E 7th Pl",
  },
  {
    name: "Sakura",
    url: "https://www.instagram.com/p/BI8EhKpg_WE/?utm_source=mp-toothpix",
    address: "4545 S Centinela Ave, Los Angeles, CA 90066",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 33.9919489,
    longitude: -118.4224101,
    doordashURL: "",
    index: 36,
    streetNumber: "4545 S Centinela Ave",
  },
  {
    name: "Connie & Ted's",
    url: "https://www.instagram.com/p/BI8EZOhAE-u/?utm_source=mp-toothpix",
    address: "8171 Santa Monica Blvd, West Hollywood, CA 90046",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.091184,
    longitude: -118.3672417,
    doordashURL: "",
    index: 37,
    streetNumber: "8171 Santa Monica Blvd",
  },
  {
    name: "Pine & Crane",
    url: "https://www.instagram.com/p/BI8ETFeg149/?utm_source=mp-toothpix",
    address: "1521 Griffith Park Blvd, Los Angeles, CA 90026",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0905596,
    longitude: -118.2770803,
    doordashURL: "",
    index: 38,
    streetNumber: "1521 Griffith Park Blvd",
  },
  {
    name: "Norm's Restaurant",
    url: "https://www.instagram.com/p/BI8EMEPgEoQ/?utm_source=mp-toothpix",
    address: "470 N La Cienega Blvd, West Hollywood, CA 90048",
    quote: null,
    la_times_link: null,
    closed: null,
    latitude: 34.0799624,
    longitude: -118.3762805,
    doordashURL: "",
    index: 39,
    streetNumber: "470 N La Cienega Blvd",
  },
  {
    name: "Mariscos Jalisco",
    url: "https://www.instagram.com/p/BI8D_K-gQJp/?utm_source=mp-toothpix",
    address: "3040 E Olympic Blvd, Los Angeles, CA 90023",
    quote:
      "The truck is parked in its usual spot, and we acquire paper platesful of the tacos, fried crisp around the edges but pliable toward their bellies, drenched with a fresh chop of tomatoes and onions, with ripe avocado on the side. The taco tastes of salt and corn and clean oil, and then, as you crunch through it, of fresh shrimp. I ask Ortega where he buys his seafood, and as always he changes the subject. I conjecture whether the slight creaminess around the shrimp comes from potatoes, bechamel or cheese, and as always, he smiles and shrugs. They are his secrets. He hopes they will make his daughters rich",
    la_times_link: null,
    closed: null,
    latitude: 34.0209613,
    longitude: -118.2128452,
    doordashURL: "",
    index: 40,
    streetNumber: "3040 E Olympic Blvd",
  },
];
